version: '2.4'

services: 
    sonarqube:
        image: sonarqube:8.5.0-community
        ports:
            - "9000:9000"
        environment:
            # - sonar.jdbc.url=jdbc:postgresql://postgresql:5432/sonar
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonarpasswd
            - sonar.jdbc.url=jdbc:postgresql://postgresql:5432/sonar
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
        depends_on:
            - postgresql
        networks:
            - sonarnet

    postgresql:
        image: postgres:13.0
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonarpasswd
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
        networks:
            - sonarnet

    nginx:
        image: nginx:1.19.3
        ports:
            - "80:80"
        volumes: 
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - sonarqube
        networks:
            - sonarnet

networks:
    sonarnet:
        driver: bridge

volumes:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    postgresql:
    postgresql_data: